import subprocess
import sys
from pathlib import Path

from docdr.client import DocDrClient, DocFile
from docdr.config import ActionConfig
from docdr.diff import filter_diff, parse_diff
from docdr.git import (
    checkout_or_update_branch,
    commit_and_push,
    create_or_update_pr,
    get_doc_files,
    write_updates,
)
from docdr.scanner import redact_secrets, scan_for_secrets


def get_git_diff(repo_path: str, sha: str) -> str:
    result = subprocess.run(
        ["git", "-C", repo_path, "diff", f"{sha}^..{sha}"],
        capture_output=True,
        text=True,
    )
    return result.stdout


def detect_mode(doc_files: list) -> str:
    return "bootstrap" if not doc_files else "maintenance"


def main():
    try:
        cfg = ActionConfig()
    except RuntimeError as e:
        print(f"[DocDr] Configuration error: {e}", file=sys.stderr)
        sys.exit(1)

    client = DocDrClient(base_url=cfg.api_url, license_key=cfg.license_key)

    # Get current doc files
    doc_files = get_doc_files(cfg.repo_path)
    mode = detect_mode(doc_files)
    print(f"[DocDr] Mode: {mode} ({len(doc_files)} doc files found)")

    if mode == "maintenance":
        raw_diff = get_git_diff(cfg.repo_path, cfg.github_sha)
        if not raw_diff.strip():
            print("[DocDr] No diff found, exiting.")
            sys.exit(0)

        diffs = filter_diff(parse_diff(raw_diff))
        if not diffs:
            print("[DocDr] All changed files are noise (lockfiles, bundles, etc.), exiting.")
            sys.exit(0)

        # Secret scan diffs — abort if secrets found (diffs should never contain real secrets)
        for d in diffs:
            secrets = scan_for_secrets(d.diff)
            if secrets:
                print(f"[DocDr] Secret detected in {d.path}: {secrets[0].pattern_name} at line {secrets[0].line_number}")
                print("[DocDr] Aborting to protect your credentials.")
                sys.exit(1)

        # Redact doc files before sending (may contain env var examples; redact rather than abort)
        sanitized_doc_files = [
            DocFile(path=f.path, content=redact_secrets(f.content)) for f in doc_files
        ]

        print(f"[DocDr] Sending {len(diffs)} file diffs to DocDr API...")
        updates = client.send_maintenance(
            repo=cfg.github_repository,
            diffs=diffs,
            doc_files=sanitized_doc_files,
        )
    else:
        # Bootstrap: scan repo structure
        tree_result = subprocess.run(
            ["git", "-C", cfg.repo_path, "ls-files"],
            capture_output=True, text=True,
        )
        tree = redact_secrets(tree_result.stdout)

        # Read manifest files and redact before sending
        manifest_names = ["pyproject.toml", "package.json", "Cargo.toml", "go.mod", "requirements.txt"]
        manifests = []
        for name in manifest_names:
            p = Path(cfg.repo_path) / name
            if p.exists():
                raw_content = p.read_text()[:2000]
                manifests.append(DocFile(path=name, content=redact_secrets(raw_content)))

        print("[DocDr] Bootstrap mode: generating initial documentation...")
        updates = client.send_bootstrap(
            repo=cfg.github_repository,
            tree=tree,
            manifests=manifests,
        )

    if not updates:
        print("[DocDr] No documentation updates needed.")
        sys.exit(0)

    print(f"[DocDr] Received {len(updates)} file update(s). Creating branch and PR...")

    branch_name = f"ai-docs-{cfg.github_sha[:8]}"
    checkout_or_update_branch(branch_name, cfg.repo_path)
    write_updates(updates, cfg.repo_path)
    commit_and_push(branch_name, "docs: update documentation [DocDr]", cfg.repo_path)

    pr_title = "DocDr: Update documentation"
    pr_body = (
        "Automated documentation update generated by [DocDr](https://docdr.dev).\n\n"
        "Review the changes and merge when ready. This PR was opened in Draft mode — "
        "it will never auto-merge.\n\n"
        "> This is an AI-generated update. Always review before merging."
    )
    pr_url = create_or_update_pr(branch_name, pr_title, pr_body, cfg.repo_path)
    if pr_url:
        print(f"[DocDr] Draft PR opened: {pr_url}")
        pr_status = "proposed"
    else:
        print(f"[DocDr] Pushed to existing branch: {branch_name}")
        pr_status = "updated"

    try:
        client.report_pr(
            repo=cfg.github_repository,
            mode=mode,
            status=pr_status,
            branch=branch_name,
            pr_url=pr_url,
        )
    except Exception as e:
        print(f"[DocDr] Warning: failed to report PR event: {e}", file=sys.stderr)


if __name__ == "__main__":
    main()
